spring:
  application:
    name: MobilePaluwagan
  profiles:
    active: dev

---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: intrudoorcaps@gmail.com
    password: wtpy blxx uwnv rcim
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/mobilepaluwagan
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: backup
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.bialnvehadzzryfbzwol
    password: Supabase123!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

---
jwt:
  secret: ${JWT_SECRET:a9f8b7c6d5e4f3g2h1i0jklmnopqrstuvwxyz123456}